### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by 4194304** [shaggyz/openbox-tenebris#1]
For a project I'm currently working on, it includes your theme.

Without a license, as GitHub states, "However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work." This in short, means that nobody can create modifications or redistribute it without legal issues.

I would highly suggest adding a license, so I (and others) would be able to build on this and distribute it with attribution (before I realized it had no license, I scaled it to 1.25x, 1.5x, 1.75x, 2x, 2.5x, 3x, 4x, and 5x!)

Licensing is quite the headache, and if there isn't a license present, I'd have to find another theme.

I recommend using CC-BY-4.0 for this project in specific, as it allows redistribution and modification with attribution.
If you're interested in taking a look at other licenses, I recommend [choosealicense.com](https://choosealicense.com/).

Sorry for the inconvenience, but with my project I want to stay far away from legal trouble.

EDIT:
To add a license to the project, go to the license page, and copy + paste the [entire thing](https://creativecommons.org/licenses/by/4.0/legalcode.txt) into a file specifically named "LICENSE" in the root of the repository.

**Comment by markhammondwilson** [comment]
Same here! Adding a license would be great.
